### ISSUE TITLE
TCB sdk是集成在客户端还是服务器端吗？如果是集成在服务器端，你的好处是有，但感觉并不算巨大

### ISSUE THREAD

**Issue by qcxyzff** [TencentCloudBase/tcb-admin-node#1]
**请提你所需要的功能**
请清楚准确地描述你所想要的功能。

**请提出你目前想到的替代办法**
如果目前有别的替代办法，请提供给我们参考。

**其它补充信息**

**Comment by lcxfs1991** [comment]
在服务端使用（比如无服务云函数）。使用admin-node能够拥有管理员权限。
