### ISSUE TITLE
事务报错.

### ISSUE THREAD

**Issue by luka26** [TencentCloudBase/tcb-admin-node#12]
**描述问题**
按照文档例子一直报错:
{ code: 'DATABASE_REQUEST_FAILED',
  message: '[FailedOperation] (Location50841) Multi-document transactions cannot be run in a sharded cluster.',
  requestId: '1579325994363_2_35827' }
代码:
const transaction = await db.startTransaction()
const doc = await transaction.collection('test').doc('0001').get()
console.log(doc)
await transaction.commit()
**运行环境**
 - 系统: Windows
 - Node版本:8.11
 - tcb-admin-sdk:latest

**Comment by Mrjing** [comment]
你好，你的问题反馈我们正在处理中，请耐心等待

**Comment by Mrjing** [comment]
你好，你可以再试下数据库事务操作

**Comment by luka26** [comment]
可以了,谢谢
