### ISSUE TITLE
无法 通过yarn add @types/tcb-admin-node安装类型声明模块

### ISSUE THREAD

**Issue by LuHugo** [TencentCloudBase/tcb-admin-node#13]
使用Typescript开发，引入tcb-admin-node模块，提示无法找到模块。需要通过require导入或自己在.d.ts文件中声明，这样太麻烦了，既然模块中自带了类型文件，为什么不单独发布？

**Comment by Mrjing** [comment]
可以试用下@cloudbase/node-sdk这个包，这个包对typescript支持的更好些，且功能和tcb-admin-node一致的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hugo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月9日(星期天) 晚上8:37
收件人:&nbsp;"TencentCloudBase/tcb-admin-node"<tcb-admin-node@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[TencentCloudBase/tcb-admin-node] 无法 通过yarn add @types/tcb-admin-node (#13)




使用Typescript开发，引入tcb-admin-node模块，提示无法找到模块。需要通过require导入或自己在.d.ts文件中声明，这样太麻烦了，既然模块中自带了类型文件，为什么不单独发布？

**Comment by LuHugo** [comment]
@Mrjing @cloudbase/node-sdk未来是不是要取代tcb-admin-node？

**Comment by Mrjing** [comment]
是的，未来的新特性会在@cloudbase/node-sdk支持了，tcb-admin-node只做维护




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hugo"<notifications@github.com&gt;; 
发送时间: 2020年2月9日(星期天) 晚上8:46
收件人: "TencentCloudBase/tcb-admin-node"<tcb-admin-node@noreply.github.com&gt;; 
抄送: "黄静远"<837317210@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [TencentCloudBase/tcb-admin-node] 无法 通过yarn add @types/tcb-admin-node安装类型声明模块 (#13)




@Mrjing @cloudbase/node-sdk未来是不是要取代tcb-admin-node？

**Comment by LuHugo** [comment]
了解
