### ISSUE TITLE
文档能否更新全一些？

### ISSUE THREAD

**Issue by tonyzzp** [TencentCloudBase/tcb-admin-node#14]
官网的文档和在这里的文档好像不一样
我看了下源码，db.command里有非常多的接口，但文档里都没写，源码也没注释
什么时候能否把文档更新一下？现在这样用起来真的很难搞。
也没个论坛。

**Comment by Mrjing** [comment]
目前github上的文档有些落后，可以移步官方博客获取更详细的文档&nbsp;&nbsp;http://cloudbase.pages.oa.com/api-reference/server/node/initialization.html
，另外我们有云开发的微信讨论群，可以留下你的微信号吗，我拉你进群




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tonyzzp"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 晚上6:22
收件人:&nbsp;"TencentCloudBase/tcb-admin-node"<tcb-admin-node@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[TencentCloudBase/tcb-admin-node] 文档能否更新全一些？ (#14)





 
官网的文档和在这里的文档好像不一样
 我看了下源码，db.command里有非常多的接口，但文档里都没写，源码也没注释
 什么时候能否把文档更新一下？现在这样用起来真的很难搞。
 也没个论坛。

**Comment by tonyzzp** [comment]
你给的是个内网地址啊。

我微信 streamcave

**Comment by Mrjing** [comment]
抱歉，放错链接了 😂，这里对外的官网文档我们这边会尽快更新
