### ISSUE TITLE
希望提供Deno版本的服务端SDK

### ISSUE THREAD

**Issue by xbol0** [TencentCloudBase/tcb-admin-node#15]
代码里有很多模块用ts实现了，希望能够出Deno版本的SDK

**Comment by Mrjing** [comment]
近期还没有计划呢，但最近推出了服务端可以使用的openapi，可以参考下文档试用下呢https://docs.cloudbase.net/api-reference/openapi/introduction.html#ru-he-huo-qu-ping-zheng
