### ISSUE TITLE
[Q]请问这个库和@cloudbase/manager-node 功能上有哪些区别？

### ISSUE THREAD

**Issue by sonofmagic** [TencentCloudBase/tcb-admin-node#16]
**描述问题**
[Q]请问这个库和@cloudbase/manager-node 功能上有哪些区别？

**Bug重现**
重现 Bug的步骤：
1.功能看上去很类似，不知道是不是在重复造轮子

**期望的结果**
希望有推荐具体用哪个？

**Comment by Mrjing** [comment]
tcb-admin-node 目前已经不再迭代了，建议使用@cloudbase/node-sdk呢， 功能上和@cloudbase/manager-node 是有区分的，可以理解manager-node是更偏管理端一点，比如 像数据表的管理，数据表迁移，回档这些，而@cloudbase/node-sdk 更偏向于doc的具体操作, 增删查改操作

**Comment by Mrjing** [comment]
@cloudbase/node-sdk 参考这个文档 https://docs.cloudbase.net/api-reference/server/node-sdk/introduction.html

**Comment by sonofmagic** [comment]
谢谢你，
![image](https://user-images.githubusercontent.com/15621541/98336668-4acfe100-2042-11eb-81eb-5145dbf51097.png)
