### ISSUE TITLE
tcb-admin-node不支持自己的独立服务器

### ISSUE THREAD

**Issue by liudonghua123** [TencentCloudBase/tcb-admin-node#2]
**请提你所需要的功能**
我想在自己的独立服务器上使用tcb-admin-node来操作微信小程序云开发中的云数据库。

但我在app.init时候secretId、secretKey对应小程序的AppID、AppSecret，使用云数据库的时候提示SIGN_PARAM_INVALID。

**请提出你目前想到的替代办法**
希望支持这样的场景

**其它补充信息**
以下是我的测试代码
```
const app = require("tcb-admin-node");

app.init({
  secretId: "<mini-app-id>",
  secretKey: "<mini-app-secret>",
});

// https://cloud.tencent.com/document/product/876/18441
const db = app.database();

const collection = db.collection("test");

collection
  .get()
  .then(res => {
    const promiseList = res.data.map(document => {
      console.info(document);
    });
    Promise.all(promiseList);
  })
  .catch(e => {
    console.error(e);
  });

```

**Comment by lcxfs1991** [comment]
可以访问这个地址：https://www.qcloud.com/login/mp?s_url=https%3A%2F%2Fconsole.cloud.tencent.com%2Fcam%2Fcapi

然后扫码登陆后，可以获取腾讯云这边的 secretid 和 secretkey。然后就可以操作了。

未来会提供更好的方式，所以没有宣传，敬请期待。

**Comment by liudonghua123** [comment]
@lcxfs1991 Great job, I tried and it worked. Thanks.
