### ISSUE TITLE
有没有 db.removeCollection(collectionName)方法

### ISSUE THREAD

**Issue by henrylu** [TencentCloudBase/tcb-admin-node#5]
**请提你所需要的功能**
看文档和源代码有提供创建集合的方法：db.createCollection，但没有删除整个集合的方法。

**请提出你目前想到的替代办法**
希望增加 db.removeCollection(collectionName) 方法，就像在小程序控制台删除整个表的操作一样。

**其它补充信息**
无

**Comment by starkwang** [comment]
这个接口正在开发中
