### ISSUE TITLE
【建议】强烈建议将云函数部分文档添加到 小程序·云开发 的文档中

### ISSUE THREAD

**Issue by hereisfun** [TencentCloudBase/tcb-admin-node#6]
小程序·云开发 给开发者带来了很大的便利，但苦于云函数只能在小程序中调用，因此无法实现PC端的管理后台。

今天无意中发现可以借助tcb-admin-node来用腾讯云服务器调用云函数，使PC端的管理后台成为了可能。这么有用的信息希望能放到 小程序·云开发 的文档中

**Comment by jimmyjzhang** [comment]
普通服务器是可以使用tcb-admin-node调用小程序的云函数的
