### ISSUE TITLE
请问是否有rest api文档的开放计划？

### ISSUE THREAD

**Issue by wenfengand** [TencentCloudBase/tcb-admin-node#9]
**请提你所需要的功能**
请清楚准确地描述你所想要的功能。

完善的rest api文档，这样可以快速在其他语言上使用tcb。
 
**请提出你目前想到的替代办法**
如果目前有别的替代办法，请提供给我们参考。

大概可以在`tcb-admin-node`中分析出所有api，但要花费一些时间。

**其它补充信息**

**Comment by wenfengand** [comment]
看了下api不是rest, 自己根据node sdk写了个简单的[tcb admin go](https://github.com/wenfengand/tcbadmingo)，目前仅有简单的数据库访问。

**Comment by xiqingongzi** [comment]
@wenfengand Hi, 文档可以在 https://cloud.tencent.com/document/product/876/34816 找到~
